### ISSUE TITLE
GPL-659 Filter out high CT & limit of detection samples

### ISSUE THREAD

**Issue by rl15** [sanger/lighthouse#120]
**User story**
GPL-659 | As development team we want to remove samples with high CT values and results = 'limit of detection' from positives on site report to avoid waste sequencing

**Who are the primary contacts for this story**
Sonia G
Cristina A
Jeff B

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Remove samples with result = 'limit of detection' from +ves on site report (assumption: samples with the prefix are treated _like_ negatives so we wont pick them
- [ ] Remove sample if all non-missing channels are > 30. (CH1-Cq > 30 && CH2-Cq > 30 && CH3-Cq > 30)
- [ ] Although they are _like_ negatives so we don't pick them, don't store ;'negative' state against them to avoid breaking reporting

**Dependencies**
GPL-642 Parsing and persisting CT values from AP #108
GPL-654 Parse & persist new result value 'limit of detection' #115

**Additional context**

Discussed post stand up on the 24th with reference to this diagram: https://app.lucidchart.com/invitations/accept/6499b3a0-7a14-4192-b5db-1cd35b84646f

**Comment by rl15** [comment]
Jeff B wrote (Tuesday, 8 September 2020 at 08:31)

For picking samples the key data will be the Cq values from the first 3 channels (which are the SARS-CoV2 test PCR products). However, it is helpful to know the positive control (channel 4) and the calls they make as part of our ongoing comparisons, so if it is not too difficult for the LIMS team to add those as well, then I think that is safest. Finally, the Target columns are obviously hugely redundant, and so the only reason for keeping them is to be able to track if the lab changes their target, or to compare across labs which may have different targets (indeed, I think Cambridge may only use one?).

**Comment by rl15** [comment]
Rich L wrote (Friday, 25 September 2020 at 17:28)

Can you check my understanding below for the CT value features, 1) parsing + persisting data and 2) filtering samples out of positive report

...

Remove sample from pick list when following rule fires
 
High CT rule: Remove sample when one or more of CH1-Cq, CH2-Cq or CH3-Cq values over 29?
 
Q. Will CT threshold be the same for all labs?

**Comment by rl15** [comment]
Jeff B wrote (Monday, 28 September 2020 at 12:39)

The rule should fire if all non-missing channels  are > 30. (CH1-Cq > 30 && CH2-Cq > 30 && CH3-Cq > 30)
Threshold will be same for all labs, though if one lab provides fewer than three channels, it applies to as many as there are.

**Comment by KatyTaylor** [comment]
To test this and related stories (https://github.com/sanger/lighthouse/issues/126, https://github.com/sanger/lighthouse/issues/129):

In UAT:
* Make sure have deployed Andrew's stories (https://github.com/sanger/crawler/issues/108 etc.)
* Wait until some samples are imported by nightly crawler that have Ct values, or create some dummy samples in the MongoDB - we want a mix of:
    - positive samples with no Ct value data
    - positive samples with Ct values > 30
    - positive samples with Ct values < 30
    - positive samples with mixed Ct values
    - positive samples where Root Sample ID starts with 'CBIQA_'
* Run the Lighthouse 'positives on site report' & check that some samples are filtered out based on correct criteria
* Scan plate barcodes of some of above samples into UAT LabWhere
* Run Lighthouse Sentinel Sample Creation and check samples are imported based on same correct criteria
