### ISSUE TITLE
GPL-726 Whats of value in this LH box then?

### ISSUE THREAD

**Issue by rl15** [sanger/lighthouse#147]
**User story**
GPL-726 | As Process Improvement I would like a LIMS feature for the new cherrypicking process where Sample Management staff can scan a Lighthouse Lab box and see how many plates are in the box, as well as how many plates have metadata, in order to prevent lab staff starting to process plates that are not ready to be cherrypicked.

**Who are the primary contacts for this story**
Scott T (R&D)
Lesley S (R&D)
Danni W
Ian J

**Acceptance criteria**
To be considered successful the solution must allow:

- [x] Do a quick mock up for Scott T (Proposer) & Danni W (User)
- [ ] read 2D barcodes of Lighthouse boxes
- [ ] list the plates in the box, indication plates with plate map data or not with tick/cross (maybe color signpost also green/red)
- [ ] plates with plate map data to top panel, those with no plate map data to bottom
- [ ] for each plate show the number of positives on the plate (sort plates by occupancy?) *1 
- [ ] display summary below panel eg  'Total of 80 plates in box; 75 plates with plates maps, 5 without'
- [ ] Handle following error gracefully; a) Box barcode unknown b) Box empty
- [ ] Be able to scan the contents of a plate individually (sometimes the user would want to check plates scanning them one by one to take the decision by plate)

*1 It maybe more *truthful* to display the number +ves that can be picked (eg not high Ct or Cambridge controls) however if this introduces significantly more work just do the positives 

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**
Assumption this woudl be new UI in http://lighthouse-ui.psd.sanger.ac.uk/, called the 'Box buster'?

This story deprecates https://github.com/sanger/lighthouse-ui/issues/31

**Comment by rl15** [comment]
Mock up sent to Danni Scott on 5th for feedback
[GPL-726 - Whats in the box.pdf](https://github.com/sanger/lighthouse/files/5493880/GPL-726.-.Whats.in.the.box.pdf)

**Comment by JamesGlover** [comment]
Mockup converted into actual component (None of the interactivity in place, this is all hard-coded at the moment). Still a bit of work to get true-false reading as Yes-No as well. 
![Screenshot 2020-11-06 at 13 51 08](https://user-images.githubusercontent.com/1283620/98373476-320dfe00-2037-11eb-97e1-a94b60b564de.png)
