### ISSUE TITLE
GPL-731 BUG - Lighthouse +ves on site report failing (Lims submission: ‘cherry picked yes/no’ flag)

### ISSUE THREAD

**Issue by rl15** [sanger/lighthouse#151]
**Describe the bug**
Lighthouse +ves on site report failing. Root issue is query that builds the ‘Lims submission;’ which I used as ‘cherry picked yes/no’ flag is failing  - SQL packet size limits

RT 704417 
reported vai slack at 1:36pm

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by rl15** [comment]
Current state (3rd Nov @ 17:30)

1. Is deployed,
2. new report generated '201103_1711_positives_with_locations.xlsx' however
3. all LIMS submission' are 'No' when should be some 'Yes' values e.g. file 201103_0101_positives_with_locations.xlsx sample sample ending ......92018 was 'Yes'

**Comment by KatyTaylor** [comment]
Closing this as it's in the Done column
