### ISSUE TITLE
GPL-736 BUG - Small number of duplicated lines in positive reports

### ISSUE THREAD

**Issue by emrojo** [sanger/lighthouse#160]
**Describe the bug**
This week we have been experiencing a very small number of duplicated lines (around 12) in the positve reports generated, that we think could be related with bugfix update performed on Monday.

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Download a Excel positive report from lightouse -ui
2. Save as .csv (<csv_report>)
3. Run following shell commands to display the duplicated lines:
```bash
  cat <csv_report> | sort > duplicated
  uniq -d duplicated
```

Examples: 201106_1440_positives_with_locations.csv

**Expected behaviour**

The report should not have any duplication

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by Chris-Friend** [comment]
The issue appears to be with the change to batching fetching the cherrypicked samples to add to the positives report. The cherrypicked samples are fetched (through lots of JOINS) using the root sample id. However, the root sample id is not unique to a sample, and fetching on such introduces the possibility of fetching duplicates/fetching the wrong cherrypicked samples.

When there was no batching, there were no duplicate fetches on root sample id, but there was the possibility that the wrong cherrypicked samples were fetched for a positive, as they were not being uniquely identified. This is still the case now, but with batching we can also fetch for the same root sample id twice, meaning we get duplicates.

A fix for both issues would be to uniquely fetch cherrypicked samples using root sample id + other fields

**Comment by KatyTaylor** [comment]
Deployment and testing:
- [ ] Alter connection string variable names in psd-deployment project
- [ ] Run report in UAT / training - check for duplicates
- [ ] Deploy to UAT / training - inc. deploying new docker config
- [ ] Re-run report - check duplicates are gone

**Comment by KatyTaylor** [comment]
_Prod report from today 10:30:_
Num positives with locations: 574,059
Num positives total: 782,647

_Prod report from today 14:11 (after deploy):_
Num positives with locations: 574,664 (presume some must have been scanned into LabWhere)
Num positives total: 782,635 (12 fewer, as expected from removing the duplicates)

Searching for the samples that were known duplicates in the report before, I can see that they only appear twice now rather than 4 times.
However, all the samples now say 'No' for the LIMS submission column - will revert the release

**Comment by KatyTaylor** [comment]
Deployed fix today and results look good, as in above comment. Known 'duplicate' samples now have one row with 'No' and one with 'Yes', as expected if one of them has been cherrypicked and one not.
