### ISSUE TITLE
GPL-741 Should we change the +ves report file format

### ISSUE THREAD

**Issue by rl15** [sanger/lighthouse#167]
**User story**
GPL-741 | As a dev manage LIMS (Rich L) we may need to change the format of the +ves report to avoid truncating actionable data

**Who are the primary contacts for this story**
Rich L
Rich C
PAM
Ian J

**Options**

1. Remove samples form the report that are over 6 weeks old (Preferred by operations discussed stand up of 13th Nov)
2. Change the file to a text file format
3. Produce more than one file 

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] change file to sliding 6 week date window

**Dependencies**
Limit of MS files 1,048,576 rows (1048k) : https://support.microsoft.com/en-us/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3 

**Additional context**
Need for output may be superseded by New Beckman robotics package WIP Nov
+ves report at ---k rows on 20th Nov (--k/day)
+ves report at 920k rows on 19th Nov (10k/day)
+ves report at 910k rows on 18th Nov (18k/day)
+ves report at 892k rows on 17th Nov (36k/day)
+ves report at 856k rows on 16th Nov (37k/day)
+ves report at 819k rows on 13th Nov (18k/day)
+ves report at 602k rows on 1st Nov (14.7k/day)
+ves report at 336k rows on 13th Oct

**Comment by rl15** [comment]
Rich L wrote (Friday, 13 November 2020 at 16:02)
 
We have conflicting requirements from operations and PAM – this is my proposal
 
·Given that PAM are migrating to the MLWH, I’d like to change the +ves report to what operations have requested, sliding 6 week window early next week.
To ensure PAM has what it needs, if PAM is struggling to replicate the report from MLWH we will put resource on it to help. (current state tracked in RT 704189)  
 
I don’t have a plan B today, if we can’t get MLWH to give you data you need. Open to suggestions.
 
My fall back was going to be google sheets for operations however has a cell limit of 4 million which we are already over with current all positives list. It certainly fails to import from a text file of 819k samples from the +ves report  (7.3M cells)

Supported by Ops (Rich C) and PAM (Rob A)

**Comment by pjvv** [comment]
@rl15 I'm assume the window is 42 (6 * 7) days from the current day?

**Comment by rl15** [comment]
Discussed stand up with RCC on 19th agreed to change to 12 week window (this is in config) 
Start date from date tested

**Comment by rl15** [comment]
tested at 17:00ish - feedback in private slack to Philip.

**Comment by rl15** [comment]
Post release into production;
+ves report at 834k rows on 23th Nov

**Comment by rl15** [comment]
Changed to 6 week window on 11th December row count 564k
