### ISSUE TITLE
GPL-767 Create Labwhere records for control  plates on Beckman [Heron]

### ISSUE THREAD

**Issue by JamesGlover** [sanger/lighthouse#202]
These requirements were first specified in https://github.com/sanger/lighthouse/issues/194 GPL-753.

**User story**
As Sample management and R&D we would like to automatically create Labwhere records for source and control plates that will be destroyed following Beckman Cherrypicking on a robot.
Specially this is for the following scenarios:
Control plate is used in a run (these plates are single use and have unique barcodes) - these go to the bin after the run

**Who are the primary contacts for this story**
Scott T
Danni W

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Labwhere records are created for plates as for the scenarios above.

**Dependencies**
https://github.com/sanger/General-Backlog-Items/issues/76
https://github.com/sanger/lighthouse/issues/176
https://github.com/sanger/General-Backlog-Items/issues/89 (Unique control plate barcodes generated by Mixito and understood by beckman/dart)

**Additional context**
Consider adding a Labwhere endpoint to lighthouse that the Beckman method can call with a <plate barcode> and either a 
<labwhere location barcode> or a more human readable abstract location type that is translated in the lighthouse configs.
Or
Can we call Labwhere directly from the Beckman method? does labwhere have a direct API endpoint we can use? what information is required?

**Comment by SujitDey2022** [comment]
![image](https://github.com/sanger/lighthouse/assets/115623404/f2c675ad-265e-4137-995f-3ba79bbf8fd5)
