### ISSUE TITLE
GPL-766 Convert the Broker class to use a Context Manager workflow

### ISSUE THREAD

**Issue by Chris-Friend** [sanger/lighthouse#204]
**User story**
As developers, we'd like to change the Broker class to use a context manager workflow. This will simplify calling the class/publishing RabbitMQ messages/error recovery

**Who are the primary contacts for this story**
Phil
Chris F

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Update the Broker class/RabbitMQ message publish workflow to use a context manager workflow

**Dependencies**
This story originates from the review of changes required for #203 

**Additional context**
See pika documentation https://github.com/pika/pika/pull/627

**Comment by pjvv** [comment]
https://github.com/pika/pika/issues/736
