### ISSUE TITLE
GPL-770-1 Update the get cherrypicked samples queries for the new Beckman events

### ISSUE THREAD

**Issue by Chris-Friend** [sanger/lighthouse#228]
**User story**
In adopting the Beckman workflow, event reporting is changing. This will break anything dependent on these events. One such thing is the filtering for cherrypicked samples in both lighthouse and crawler. These are SQL queries which currently query for the Sentinel cherrypicking events only. They need to be updated to query for Beckman picking events **as well**.

The alternative is to fire the same `cherrypick_layout_set` event for the Beckman process, but since no real Beckman action corresponds to this event, this solution has been rejected.

**Who are the primary contacts for this story**
Katy T
Phil
Chris F

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Update lighthouse method to get cherrypicked samples to query for both Sentinel or Beckman cherrypicking events. This is used to generate the positives report.
- [ ] ~~Update crawler method<ins>**s**</ins> to get cherrypicked samples to query for both Sentinel or Beckman cherrypicking events (introduced as part of https://github.com/sanger/crawler/issues/144)~~ See https://github.com/sanger/crawler/issues/192
- [ ] (**Optional/Do as a separate task**) - have only a single implementation of these "is a sample cherrypicked" rules. See https://github.com/sanger/unified_warehouse/issues/152

**Additional context**

**Comment by harrietc52** [comment]
Do we need to back populate the `lh_sample_uuid` in the lighthouse_samples table, as 19/22 million records do not have a `lh_sample_uuid` value, therefore the JOIN may not work as intended?

**Comment by KatyTaylor** [comment]
Test this by running the positives report from lighthouse ui, and making sure the contents of the 'LIMS submission' column is correct:
* It should say 'Yes' for any samples that have been cherrypicked the Sentinel way ('cherrypick_layout_set' event)
* It should say 'Yes' for any samples that have been cherrypicked the Beckman way ('lh_beckman_cp_destination_created' event)
* It should say 'No' for other samples

**Comment by Chris-Friend** [comment]
> Do we need to back populate the `lh_sample_uuid` in the lighthouse_samples table, as 19/22 million records do not have a `lh_sample_uuid` value, therefore the JOIN may not work as intended? Could some how the combo key `root_sample_id / rna_id / result` be used to identify the correct sample uuid

Crawler's `update_mlwh_and_dart_with_legacy_samples` migration should handle this. It needs to be run before a sample can be added to DART (be processed by the Beckman workflow), and gives samples `lh_sample_uuid`s
