### ISSUE TITLE
GPL-842 New intergration point for lighthouse service, samples of importance.

### ISSUE THREAD

**Issue by rl15** [sanger/lighthouse#247]
**User story**
GPL-842 | As core LIMS we would like a new collection to persist if a sample is of importance or value to sequence

**Who are the primary contacts for this story**
Callum S (PAM)
Ryes (PAM)
Harry C
Philip VV
Eduardo MR

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] New collection with schema 
- [x] For each sample PAM are aware of add to new collection
`root_sample_id`
`must_sequence` (Sequence regardless – bypasses existing business rules)
`prferentially_sequence` (Sequence if passes existing rules)
- [x] update report generation using rules for new priority samples
- [x] set `processed = False` on each insert
- [x] use [`lookup` with `mergeObjects`](https://docs.mongodb.com/manual/reference/operator/aggregation/lookup/#use-lookup-with-mergeobjects) to get priority samples working
- [ ] set `processed = False` on each update - there seems to be a bug with the `notmalize_on_patch` setting

**Dependencies**

**Additional context**

Root sample id on it's own is not unique enough for that new collection key, it's the four fields of Root sample id, RNA ID, Result and Lab ID.

Parent feature: https://github.com/sanger/General-Backlog-Items/issues/103

**Comment by KatyTaylor** [comment]
More info (current thinking):

- PaM make an API call to the lighthouse service which makes an upsert to the new 'samples of importance' collection
- This triggers a process which:
    - checks if data for those samples is in Mongo already
    - if so, check if they have been cherrypicked already
    - if not yet cherrypicked:
        - combine information from 'filtered positive' field and 'samples of importance' to decide whether to set well state in DART to 'pickable'
        - set the 2 new fields in MLWH lighthouse_sample table (https://github.com/sanger/unified_warehouse/issues/172)

There will also need to be a change to the existing nightly crawler run, which:
- checks if the new samples have entries in the 'samples of importance' collection
- if so:
    - combine this info with the 'filtered positive' info to decide whether to set well state in DART to 'pickable'
    - set the 2 new fields in MLWH lighthouse_sample table (https://github.com/sanger/unified_warehouse/issues/172)
