### ISSUE TITLE
BUG - update positive samples report generation

### ISSUE THREAD

**Issue by pjvv** [sanger/lighthouse#255]
**Describe the bug**
Currently the positive samples report assumes the "Date Tested" field is a string and tries to convert it before getting the latest samples. With moving over to using a proper mongo date field, the query is now simpler.

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by KatyTaylor** [comment]
Closing this, as it's in the Done column
