### ISSUE TITLE
BUG - API mistakenly reports "no plate map data"

### ISSUE THREAD

**Issue by pjvv** [sanger/lighthouse#292]
**Describe the bug**
When a plate is queried and the plate has no fit to pick samples, the API mistakenly reports that there is no plate map for this barcode.

**To Reproduce**
Steps to reproduce the behaviour:
1. Query a plate (`/plates/?barcodes[]=<barcode>`) which has no fit to pick samples

**Expected behaviour**
The response should state that there is plate map data regardless of the other data in the response.

**Additional context**

**Comment by KatyTaylor** [comment]
Closing this, as it's in the Done column
