### ISSUE TITLE
DPL-008 BUG - phenotype should be lowercase in all cases

### ISSUE THREAD

**Issue by emrojo** [sanger/lighthouse#296]
**Describe the bug**
From comment in pull request:  https://github.com/sanger/lighthouse/pull/266/files
```
# The result value in the phenotype in MLWH.sample is all lowercase,
# because it is converted in create_post_body in helpers/plates.py,
# whereas in the original data in MongoDB and MLWH.lighthouse_sample it is capitalised
in helpers/reports.py

I've recently found examples in the sample table where phenotype starts both with upper and lower case letters. Therefore we should probably convert both columns to lower case before merging (in add_cherrypicked_column) method, rather than just converting one.

```

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. There are samples in the phenotype with 'Positive' and 'positive'

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by stevieing** [comment]
DPL-030. Once done we can recheck. Might fix the code bit but not the data.

**Comment by SujitDey2022** [comment]
Closing and moving the bug to the done state based on the comments shared in https://docs.google.com/spreadsheets/d/14Rh3Q1l_d1tqcxZy6wploMXQV_kSiBfamkaJzwgjt8E/edit#gid=0
