### ISSUE TITLE
GPL-967 UAT Action - Setup Cherrypick Test Data Endpoints [Heron]

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/lighthouse#322]
**User story**
As part of the Site Acceptance Testing (SAT) team testing the two Biosero systems, we will need a repeatable way to create testing data for input into the test runs in the UAT environment. Ideally this data creation method should not require in depth knowledge of the technical way the data is created.

**Who are the primary contacts for this story**
Philip
Andrew

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Creation of a new POST endpoint `/cherrypick-test-data`, with the information for generating a new test run. Including number of plates, number of positives, addToDart flag. (This end point may have already been created as a stub from [GPL-969](https://github.com/sanger/lighthouse-ui/issues/73))
- [x] A new collection is created in Mongo DB to store the Test Run Data. 
- [x] Endpoint, step 1: method should first generate plate specifications and add them to a document in a new collection in Mongo, returning the ID of the row.  The document should contain the plate specifications, whether to add to DART, timestamps for created_at and updated_at as well as a status of pending for the run.
- [x] Endpoint, step 2: method should finally send a POST to Crawler's API via `/cherrypicker-test-data` with the ID of the run in the request body as JSON.
- [x] A 201 is returned if Crawler creates the test run data and updates Mongo with a completed status. The id of the test run data row in the new Mongo collection is returned. 
- [x] A 422 should be returned when the validation of the inputs for the endpoint fail.
- [x] A 500 is returned if the creation of test run data by Crawler is unsuccessful.
- [x] A second GET endpoint `/cherrypick-test-data/id-xyz` gets the data about a specific test data generation run, including the status, the reason for failure if appropriate otherwise the metadata for barcodes that can be used for printing barcodes.
- [x] A third GET endpoint `/cherrypick-test-data` gets all the available cherry picker test data objects with their status so that they can be listed in the UI.

**Dependencies**
This story is blocked by the following dependencies:
None.

**Additional context**
The existing way to create such data for Beckman is to use the python script that generates Crawler plate map files and printer files (for the Lighthouse-UI print source barcodes screen). This involves technical knowledge to run the python script, and to get the resulting plate map files into the Crawler docker container and to run it.
Supply a screen in Lighthouse-UI UAT that lets anyone generate data, which could create and insert the files into the Crawler docker container and trigger a run. 
Should allow the user to say how many plates they want with how many pickable samples e.g. 10 with 1, 2 with zero, 1 with 96. And summarise the barcodes made and numbers of pickable wells for reference (allow cut and paste or printable version).
It could still create a print file as before (labels are not always required) or trigger the print directly with a printer selector dropdown and print button.

LucidChart diagram [here](https://lucid.app/lucidchart/invitations/accept/inv_1b8208a2-17e8-498d-a301-bf34b64f3c6d) showing Lighthouse UI mock ups and UAT Action process

**Comment by harrietc52** [comment]
LucidChart diagram here showing Lighthouse UI mock ups and UAT Action process
