### ISSUE TITLE
GPL-970 Biosero - Lighthouse API refactor and representation in Postman [Heron]

### ISSUE THREAD

**Issue by pjvv** [sanger/lighthouse#323]
**User story**
As a dev team we would like to refactor the lighthouse API in order to continue serving Beckman requests as is but have a more generic request strategy for Biosero (and future).

An option would be to use versioning / (which translates to v1) for Beckman calls and /v2 for Biosero and future calls.

Another option - check for the existence of `automation_system` data in body.

**Who are the primary contacts for this story**
Philip
Andrew
Eduardo

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] implement API versioning or,
- [ ] refactor routes to support both Beckman and Biosero
- [ ] update Postman API to reflect these changes

**Dependencies**
This story is blocked by the following dependencies:
Postman API for existing Lighthouse endpoints

**Additional context**
Updating the API calls from Beckman is probably costly and unfeasible so we need to continue to support these calls.

**Comment by KatyTaylor** [comment]
This could be done as part of this refactor - https://github.com/sanger/lighthouse/issues/341

**Comment by andrewsparkes** [comment]
Determined that this story not required as we did not want to re-use existing Beckman endpoints.
