### ISSUE TITLE
GPL-976 Biosero - Create partial source plate event endpoint [Heron]

### ISSUE THREAD

**Issue by pjvv** [sanger/lighthouse#328]
**User story**
As a Biosero API user I would like an API endpoint that allows me to record the creation of a partial source plate event in the LIMS.

**Who are the primary contacts for this story**
Philip
Andrew

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] endpoint accepts a source plate barcode, automation_system_run_id, and event_type
- [ ] endpoint looks up the information on the source in the central database via the micro webservice
- [ ] endpoint creates the partial source plate event in MLWH 

**Dependencies**
This story is blocked by the following dependencies:
API schema development
Previous endpoint story

**Additional context**
This is for when a source plate is partially picked (the destination has no more room) and is re-sealed and returned to the input stacks. We would like to record an event which records which samples have been picked from it in this specific run. NB. it is possible for a source to be partially picked over multiple runs, so it could end up with several such events.

**Comment by KatyTaylor** [comment]
Closing this, as it's in the Done column
