### ISSUE TITLE
GPL-978 Biosero - Create partial destination plate event endpoint [Heron]

### ISSUE THREAD

**Issue by pjvv** [sanger/lighthouse#329]
**User story**
As a Biosero API user I would like an API endpoint that allows me to record the creation of a partial destination plate event in the LIMS.

**Who are the primary contacts for this story**
Philip
Andrew

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] endpoint accepts a destination plate barcode, automation_system_run_id, event_type
- [ ] endpoint selects the required information from the central database via microservice endpoint
- [ ] endpoint then creates the partial destination plate event in MLWH events database

**Dependencies**
This story is blocked by the following dependencies:
API schema development

**Additional context**
The goal here is to have an event that contains the partial destination plate details (controls and samples).

**Comment by KatyTaylor** [comment]
Closing this, as it's in the Done column
