### ISSUE TITLE
GPL-979 Biosero - Create destination plate endpoint [Heron]

### ISSUE THREAD

**Issue by pjvv** [sanger/lighthouse#330]
**User story**
As a Biosero API user I would like an API event endpoint that allows me to trigger the creation of a destination plate in the LIMS.

**Who are the primary contacts for this story**
Philip
Andrew

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] endpoint accepts a destination plate barcode, event_type, event_source (from config e.g. 'biosero')(automation_system_run_id could be also sent, to allow a check on the plate that this run is the latest against that plates wells)
- [ ] endpoint looks up the information for the destination in the central database via the micro webservice
- [ ] endpoint then creates the destination plate in Sequencescape (see existing similar Beckman endpoint)

**Dependencies**
This story is blocked by the following dependencies:
API schema development

**Additional context**
Check, can we modify the existing destination creation endpoint that Beckman calls, and have the Beckman route use the DART to lookup data and the Biosero route rely on data sent in the body of the POST. The Sequencescape process should be identical.

**Comment by KatyTaylor** [comment]
Closing this, as it's in the Done column
