### ISSUE TITLE
GPL-473 Provide endpoint for PAM to update LH sample with yes or no ‘Value in Sequencing

### ISSUE THREAD

**Issue by rl15** [sanger/lighthouse#35]
**User story**
GPL-473 | As Stakeholders in sampling strategy (Keith A, Rob A & John S) we would like an endpoint that for a given root sample id updates value in sequencing with yes or no for SSR to use this in +ves lighthouse samples on site (see GPL-472)

**Who the primary contacts are for this story**
Rich L
Rich C
Christoph P (PAM)
Danni W (SM)
**Acceptance criteria**
Please see:
https://ssg-confluence.internal.sanger.ac.uk/x/iKMKBg
Sequence flow diagram, messages from SSR Actor to Sample crawler

To be considered successful the solution updates fields:

1. Lighthouse samples all start initially with field 'value in sequencing' set to 'unknown', with updated date set
2. Via API for a given root sample ID allow value to be set to yes or no + updated date
3. New fields in report available at  https://psd.pages.internal.sanger.ac.uk/lighthouse_reports/ of
> 4. value in sequencing {yes, No, Unknown}
> 5. Date value in sequencing set

**Additional context**
Is it wise to have a preshared API key for this?
API will be given 1-? values to update (probably few 10k)

**Comment by emrojo** [comment]
**Update on acceptance criteria (from mail chain 9/Jun/2020)**

* LIMS service receives a request to http/s api endpoint from a server inside the Sanger intranet
* The request has a secret key as header
* Service needs to support: 
  - At initial stages, uploading the update of 50.000 - 100.000 samples once/twice every week
  - In future, receiving a delta (diff of samples) with 100-1000 once/twice a week
* All samples will be assigned a time and date (value_in_sequencing_updated_at)  that will correspond with the time and date when we received this request in LIMS.
* The message of the request will contain a list of samples information with:
 - Root Sample ID
 - Value in sequencing (Y/N)
 - Date when value in sequencing is declared
* If we receive the same sample id again, we will update its Y/N value in value_in_sequencing and the date in value_in_sequencing_updated_at.
* In case of success, the answer will be the same list of samples with the updated values. It will return a HTTP success code (200).
* In case of error it will return a HTTP error (5xx, 4xx) depending in the condition.
* The error conditions in message:
 - Root sample id not present (5xx)
 - Incorrect message format (4xx)
* In case of error,  apply the message partially with all right samples and receive back a list of successful and error updates
* The automatic report of positive samples on site will be generated with current settings of value_in_sequencing and value_in_sequencing_updated_at

**Comment by harrietc52** [comment]
`# curl -X POST http://127.0.0.1:5000/samples_declarations -d '[{"root_sample_id": "0012", "declared_at": "2013-04-04T10:29:13"}, {"root_sample_id": "0012", "declared_at": "2013-04-04T10:29:13"}, {"root_sample_id": "0010", "declared_at": "2013-04-04T10:29:13"}, {"root_sample_id": "0011", "declared_at": "2013-04-04T10:29:13"}, {"root_sample_id": "0011", "declared_at": "2013-04-04T10:29:13"}]' -H 'Content-Type: application/json'`

**Comment by harrietc52** [comment]
# eg "2013-04-04T10:29:13"
# By default eve DATE_FORMAT is set to RFC1123 standard which is %a, %d %b %Y %H:%M:%S GMT

**Comment by harrietc52** [comment]
Performance
10000 samples = 14s
20000 samples = 30s
30000 samples = 69s
40000 samples = 102.94s

**Comment by rl15** [comment]
Requested update from PAM Friday, 26 June 2020 at 09:44

**Comment by rl15** [comment]
Christoph P writes Friday, 26 June 2020 at 12:53

Hello again,
have done some testing now. Can confirm that the service is working well, many thanks! Error messages are also very clear, which is helpful. Couple of things to make you aware of - none of these is critical, but you might want to look into them:
when providing a JSON with errors, I do not get the full result (with fields "_updated", "_created" etc) for the records that are okay, so unclear whether they were registered or not (I think we agreed to accept the correct records and just fail the incorrect ones, see further down in the thread). Would be good to get clarity of what is happening.
when providing a JSON with a missing sample ID, I do not get a JSON with error message, but an html with "internal server error"
when re-uploading sample IDs, I would expect the "_updated" and "_created" to differ in the response, but they are always the same and show the most recent submission
Cheers,
Christoph
