### ISSUE TITLE
DPL-037 Beckman endpoint should check for existing sample (C=M)

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/lighthouse#351]
**User story**
DPL-037 As someone reporting on the Heron data, I would like the Beckman plate creation endpoint to :
- check whether the relevant samples already exist already in Sequencescape, and 
- use them if exist
so that we avoid creating duplicate records, with differing COG UK IDs, for the same sample.

**Who are the primary contacts for this story**
Katy, Harry, James M, Sara

**Acceptance criteria**
When the Beckman plate creation endpoint is called from the Beckman software, or from the page where you manually scan the destination plate barcode in:
- [ ] Destination plate is created
- [ ] Wells on that plate are filled with either new samples, or existing samples (or a mixture), depending on whether the samples already exist in Sequencescape
- [ ] Match samples based on root sample id (description), source / stock plate barcode, well position on that plate, and result (phenotype).

**Additional context**
- Not sure how hard this will be. Might need some research first.
- The other way around (Beckman first, then Sentinel) was considered and decided it was low risk, so not being actioned at this time (https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Duplicate+COG+UK+IDs+May+2021, 1st agenda question point b)

**Comment by KatyTaylor** [comment]
@andrewsparkes @emrojo do you know if the endpoints that create samples in SS will remain our responsibility, or transfer to PaM? Thanks

**Comment by TWJW-SANGER** [comment]
Viewed as unlikely to happen now that all Heron samples go through the Beckman robot only and all samples are allocated a COG UK Id on creation.
