### ISSUE TITLE
DPL-045 | Testing of 'Important samples in UAT 7/7 (messages good, did what it expected) and PROD w/c 12/7 (hand hold first few runs/ runs daily)

### ISSUE THREAD

**Issue by rl15** [sanger/lighthouse#373]
**Description**
DPL-045 | Testing of 'Important samples in UAT (messages good did what it expected) and PROD (hand hold first few runs/ runs daily)

Reminder of context (work completed in March)

https://github.com/sanger/unified_warehouse/issues/172
https://github.com/sanger/lighthouse-ui/issues/51
https://github.com/sanger/crawler/issues/256

**Who the primary contacts are for this work**
Sonia G (PAM)
Callum S (PAM)
Rhys (PAM)
Sara S (Operations)
Rich L

**Plan**
- [ ]  Test that messages from PAM to LIMS endpoint are ok and expected plats in Box buster are flagged as preferentially sequence in UAT (NB Unwelcome complexity  to test in UAT ue to MLWH updating weekly and UUID complexity from Mongodb)
- [ ] Production test - put aside time to check the first week of runs. Process runs daily 

**Uncertainty**

What time will the messages be sent in prod from PAM?

**Context**

PAMs view of the software components:  https://miro.com/welcomeonboard/SlhUeVVNTUpuSGZWQ21zV1Q2a0VFODR5YXlKdDBKMVQ2dEs2RklSRkxsSWhtOFRzYjQ5dHRia2E0VUVWV25tSXwzMDc0NDU3MzU5MDk3MjMzNDAy

**Comment by rl15** [comment]
Expecting test in UAT on 28th June

Need to understand what plate(s) on hat box wil be flagged as *Preferentially sequence* http://uat.lighthouse-ui.psd.sanger.ac.uk/box_buster

**Comment by rl15** [comment]
Test to complete

PAM/Surveillance want to test that is a set of samples are flagged a preferentially sequence i run in error can we hot fix back to null

1. On a given date PAM will send RT to reset priority samples flag for a given date (these will be set to true)
2. We reset those samples to null (options is also false as bread crumb?)
3. Close ticket

**Comment by emrojo** [comment]
The wells priorities of any plate can be altered using the priority samples API as long as they haven't started picking from the plate.

Steps to test it:
[ ] - Create a new plate in mongo/mlwh/dart
[ ] - Change the status of any of the samples of the plate with any of the changes options (see below)
[ ] - Check the state of the well in DART  has state='pickable'
[ ] - Rollback the status of any of the samples of the plate with any of the changes options
[ ] - Check the state of the well in DART has changed to state=''

Options:
*NB* These options will be applied on every crawler run, so after making the change we may have to wait 15-30 mins.
A - Send a request with the API using same messages that PAM uses with payload:
    - Change of priority (preferentially_sequence or mandatory_sequence)
    - Change of flag 'processed' to False
B - Run a mongo update with same changes as before

**Comment by rl15** [comment]
https://rt.sanger.ac.uk/Ticket/Display.html?id=725917

**Comment by emrojo** [comment]
This was the mongodb update to change priority samples for today: 

```
db.priority_samples.updateMany({"preferentially_sequence": true, "processed": true, "_created": {"$gte": ISODate("2021-07-15T00:00"), "$lt": ISODate("2021-07-16T00:00")}}, {"$set": {"processed": false, "preferentially_sequence": false}})
```

**Comment by KatyTaylor** [comment]
Closing this, as it's in the Done column
