### ISSUE TITLE
DPL-nnn [BUG] Reports not correctly generated

### ISSUE THREAD

**Issue by emrojo** [sanger/lighthouse#473]
**Describe the bug**
Because of the high number of samples received has increased a lot in the last period, the positive reports generated are exceeding the supported maximum size and are failing on creation.  

Options:
1. Deprecate this view (to my knowledge nobody is using this reports view anymore but we need to double check with SSRs
2. Increase the size of dates that are needed for the report to be generated
3. Not doing anything, and wait until the number of samples is low enough, so the report can be created again

Option 3 will happen automatically at some point if we don't take any decision about how to solve this.

**RT Ticket Number**
If applicable

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to reports view
2. All reports with a failure on creation have 0 size

**Expected behaviour**
All reports are create correctly

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by Skrich1999** [comment]
This is not a report used by SSRs and speaking with the Data QC team, this is not a report they run either. I have emailed James Mack and Sara Stott (8/4/22).
I propose this ticket can be closed as this is the expected outcome.  It can be opened again if needed.

**Comment by KatyTaylor** [comment]
@Skrich1999 did James M and Sara get back to you about whether they use this report?

Thanks

**Comment by Skrich1999** [comment]
@KatyTaylor Just to say, I have had No reply back,  Let me know if you have this in hand now or need me to push hard for a reply.

**Comment by stevieing** [comment]
Confirmed that these reports are no longer needed. Closed in favour of #563
