### ISSUE TITLE
DPL-254 Changes in picking action for samples coming by RabbitMQ so COG-UK Ids are generated by GSU

### ISSUE THREAD

**Issue by emrojo** [sanger/lighthouse#509]
**User story**
As PSD/GSU I want to not update lighthouse_sample (cog_uk_id) when picking a sample because the setting of the cog_uk_id for a sample is going to happen in GSU side of the application.

**Who are the primary contacts for this story**
Eduardo Martin
Andrew Sparkes

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Any sample created from RabbitMQ should not update lighthouse_sample
- [ ] Any sample created from SFTP should still generate cog_uk_id
- [ ] The changes should apply to both robots architecture (Beckman and Biosero) because they use two different code sources
- [ ] The result of this story should solve this related story: https://github.com/sanger/lighthouse/issues/429

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- [#429](https://github.com/sanger/lighthouse/issues/429)
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by sdjmchattie** [comment]
Tests have been performed on Sentinel that demonstrate that those samples with a given COG UK ID in MongoDB (RabbitMQ messages provide this) are not updated with new barcodes when the Sentinel endpoint is called.  Those without a COG UK ID in MongoDB are given one when the endpoint is called and updated in MLWH.

Similar tests have been performed for Biosero using the integration test script in https://github.com/sanger/biosero-sql.

We don't have a working model of the Beckman process, so we will monitor the first pick on the Beckman machine after deployment to production.
