### ISSUE TITLE
DPL-468 - Data fixes overview

### ISSUE THREAD

**Issue by Jonnie-Bevan** [sanger/lighthouse#533]
**User story**
PAM have identified various data issues. These could (should?) be made into separate issues to track, but I'm making a central ticket for them for the moment. See the table below for specific information regarding the data issues.

Priority | Field | Issue | Action | Ready for PSD
-- | -- | -- | -- | --
1 | All | [Randox uploaded incorrect plate maps in June 2021. As such the root sample ID associated with these samples is incorrect](https://github.com/sanger/lighthouse/issues/546) | Mark all samples as consent withdrawn | Yes
2 | Date tested | [Brants Bridge date tested in future](https://github.com/sanger/lighthouse/issues/547) | DONE | Yes
3 | Date tested | [LSPA date tested in future](https://github.com/sanger/lighthouse/issues/548) | ~Plate CHERY00002524 was sent in mdy format. Change date tested to dmy. 10/01/2022.~ DONE | Yes
4 | Root sample ID | [Root sample ids irregular](https://github.com/sanger/crawler/issues/502) | AK to continue to work with PSD to assess criteria. MK is in Progress. Cambridge to fix. | No
5 | Root sample ID | [Brants Bridge sent root sample ids in incorrect format](https://github.com/sanger/lighthouse/issues/556) | Plate 95040456002133259 had non clinical samples and duplicated samples. Remove Test sample and duplicates according to attached plate map and correct root sample IDs for original sample. | Yes
6 | RNA ID/Plate Barcode | [Brants Bridge sent ~1500 samples with incorrect RNA ID](https://github.com/sanger/lighthouse/issues/557) | Correct data received for 1063 samples, AK chasing up remaining 445 | No

**Who are the primary contacts for this story**
Alan K
Jonnie B

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Randox sample IDs from June 2021 fixed
- [x] Brants Bridge incorrect dates fixed
- [x] LSPA incorrect dates fixed
- [ ] Root Sample IDs fixed (see DPL-048-1)
- [ ] Brants Bridge Root Sample IDs fixed
- [ ] Brants Bridge RNA IDs fixed

**Comment by TWJW-SANGER** [comment]
For sub-issues 4,5,6 we will say all affected samples to be marked sample withdrawn with no further corrections.

**Comment by TWJW-SANGER** [comment]
Deprecated by the Product Owner.
