### ISSUE TITLE
DPL-048-2: malformed root_sample_ids without duplicates in MLWH, unpicked

### ISSUE THREAD

**Issue by Jonnie-Bevan** [sanger/lighthouse#536]
**User story**
Part of the wider [DPL-048-1](https://github.com/sanger/crawler/issues/502) issue which spawned in turn from [DPL-048](https://github.com/sanger/crawler/issues/375). Related are [DPL-0483-3](https://github.com/sanger/lighthouse/issues/537), [DPL-0483-4](https://github.com/sanger/lighthouse/issues/538) and [DPL-0483-5](https://github.com/sanger/lighthouse/issues/539).

This story concerns the 4,699 malformed root_sample_ids in the MLWH `lighthouse_sample` table. These came from the MK lighthouse lab in August 2021 and have an extra substring (something like '_RNA123456789') concatenated on the end of the correct ID. 

**Fix**
Since these samples were never picked they are not in SequenceScape, Event Warehouse or the MLWH `sample` table, so the only places that these need to be fixed are in the MongoDB `sample` table and MLWH `lighthouse_sample` table.

These can be fixed by using a script to correct the ID (remove everything after underscore) and then updating the relevant row with the correct ID. 

**Who are the primary contacts for this story**
Jonnie B
Alan K

**Acceptance criteria**
- [ ] data are fixed in MLWH lighthouse_sample table
- [ ] data are fixed in MongoDB sample table
- [ ] have double-checked that this data does not exist in SS/Ev. Warehouse/MLWH Sample table.

**Comment by KatyTaylor** [comment]
Closing, as is in Done column.
