### ISSUE TITLE
DPL-473 - Brants Bridge sent ~1500 samples with incorrect RNA ID

### ISSUE THREAD

**Issue by Jonnie-Bevan** [sanger/lighthouse#557]
A data fix requested by PAM, sixth priority from https://github.com/sanger/lighthouse/issues/533.

**Description**
Brants Bridge sent ~1500 samples with incorrect RNA ID. The correct data was received for 1063 of these, though Alan K is still awaiting the remaining 445 samples. Ideally these should be corrected in the MLWH database (lighthouse_sample table). They should also be dealt with in the MongoDB and any other databases/tables they may appear in (the MLWH sample table, SequenceScape, Events Warehouse).
There is a chance these samples were picked and sequenced, and if so it may be needed to get NPG involved.

**Main Contacts**
Alan K

**Comment by TWJW-SANGER** [comment]
Deprecated by the Product Owner
