### ISSUE TITLE
DPL-429 As developer I want to remove the lighthouse reports generation as is not in use anymore and want to have less code to maintain

### ISSUE THREAD

**Issue by emrojo** [sanger/lighthouse#608]
**User story**
As developer I want to remove the lighthouse reports generation as is not in use anymore and want to have less code to maintain

**Who are the primary contacts for this story**
Eduardo Martin
Stuart McHattie
Andrew Sparkes

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Stop generating the lighthouse positives reports in lighthouse app

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by sdjmchattie** [comment]
It looks like this is captured in #722 so I will close this issue
