### ISSUE TITLE
DPL-629 Check status of Heron CP plates

### ISSUE THREAD

**Issue by neilsycamore** [sanger/lighthouse#701]
As Heron sample management (Kristina B) we have some plates that came up in our destruction process as being neither on our keep or destroy list please could it be checked against our criteria.

As defined in DPL-494                                                                                              
Criteria 1             Keep all plates for all samples tested in 2020.                                                                                
Criteria 2             Keep all plates that had negative samples tested between January 2021 and April 2022 (inclusive).                                                                                
Criteria 3             Keep all the ONS samples (but check to see how many extra plates this would be).           
Please could you check these plates and let me know if we need to retain them?

**RT Ticket Number**
[769846](https://rt.sanger.ac.uk/Ticket/Display.html?id=769846)

List of plates
[Anomalies for PSD.xlsx](https://github.com/sanger/lighthouse/files/10433816/Anomalies.for.PSD.xlsx)

**Comment by sdjmchattie** [comment]
The work for this was completed in GitLab where the merge request is: https://gitlab.internal.sanger.ac.uk/psd/data-patch-archive/-/merge_requests/16
