### ISSUE TITLE
GPL-584 Archive old LH +ves on site reports

### ISSUE THREAD

**Issue by emrojo** [sanger/lighthouse#78]
**User story**
Every day a new report with estimated size 5mb is created in filesystem. As it is not very useful to keep very old reports and we can run out of disk spaces eventually, I suggest to modify reports to remove old copies and keep a reasonable number (last 20?).

**Who are the primary contacts for this story**
Eduardo Martin

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Keep the number of reports under 20.

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by KatyTaylor** [comment]
Closing this as it's in the Done column
