### ISSUE TITLE
DPL-821 [RVI] Cherry-picking LSW-96 Stock plates using the existing Tecan systems

### ISSUE THREAD

**Issue by SujitDey2022** [sanger/lighthouse#795]
**User story**
As the automation lead for RVI Cherry-picking (Scott T), I need to establish the feasibility of cherry-picking LSW-96 Stock plates using the existing Tecan systems in order to determine if an interim cherry-picking approach for RVI is possible and practical. 

**Who are the primary contacts for this story**
Scott T (R&D)
Rich C (SSR)
Tobi A (R&D)
Lesley S (R&D)
Abby C (R&D)

**Who is the nominated tester for UAT**
Scott T
Rich C

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] Identify the processes and services required to create a Tecan .gwl file from LSW-96 Stock plates and transfer it to the Sample Preparation drop box.
- [x] Identify the processes and services required to create the picklist paperwork associated with Tecan .gwl files.
- [ ] Produce a process map illustrating the steps involved, including the services and personnel (if relevant) required in the process
- [x] Produce a document detailing the process (confluence page/google doc or similar)

**Background**

The Respiratory Virus and Microbiome Initiative (RVI) project is looking to utilise the equipment and systems set up for COVID sequencing to sequence respiratory viruses more broadly.
We plan to use the Biosero cherry-picking systems in the GSLP labs long term, but it has become clear that we will need to make significant changes to the robot program and LIMS logic to accommodate the flexible cherry-picking approach that RVI requires.
The final scope, as currently understood, will require significant work from PSD and Biosero, which is likely to take months to implement. 
We have discussed using the Tecan instruments as an interim solution on the RVI project calls. If we can use the existing cherry-picking process (possibly with minor alterations) then we could start cherry-picking at a much earlier stage while we are still working on the Biosero implementation.
There are many unknowns around this proposed approach and therefore a research story is required to establish if this is a feasible and practical approach.

**Details**

- We would like to cherry-pick by volume, with no normalisation step.
- The exact volume is not known at this stage, but is likely to be either 35µl or 50µl.
- Source plates will be PerkinElmer shallow-well 96-well plates or Biorad hardshell shallow-well 96-well plates
- These may need to be individually specified in the .gwl file, however we may be able to assume Biorad hardshell for all plates
- Destination plates will be PerkinElmer shallow-well 96-well plates or Biorad hardshell shallow-well 96-well plates
- We may not need to specify as these two plate types are interchangeable on all automation platforms.
- The samples to be cherry-picked would be selected by GSU.
- This could include both COVID ‘positive’ (fit to pick) and Covid ‘negative’ samples.
- Positive and negative controls may be added to the plate
- This is likely to use new control plate. Previous control plates set up for the Heron process include:
[DN626424D](https://sequencescape.psd.sanger.ac.uk/labware/27056272)
[DN845929S](https://sequencescape.psd.sanger.ac.uk/labware/27253412)
Cherry-pick ‘destination’ plates may be used as ‘source’ plates for further cherry-picks 

**References**
RT Ticket - #782994

**Additional context**
Email trail to SSRs attached along with SOPs provided by SSRs detailing the Heron Tecan cherry-picking process that was implemented in 2020.
[ATT00001.txt](https://github.com/sanger/lighthouse/files/11980490/ATT00001.txt)
[Lighthouse Cherrypicking.docx](https://github.com/sanger/lighthouse/files/11980496/Lighthouse.Cherrypicking.docx)
[Lighthouse Labs Box Manifest SOP.docx](https://github.com/sanger/lighthouse/files/11980497/Lighthouse.Labs.Box.Manifest.SOP.docx)
[Heron SOPs.docx](https://github.com/sanger/lighthouse/files/11980498/Heron.SOPs.docx)
[SM_PRO_0116 Cherry picking using the Tecan robot with disposable tips V1.4 draft.docx](https://github.com/sanger/lighthouse/files/12078737/SM_PRO_0116.Cherry.picking.using.the.Tecan.robot.with.disposable.tips.V1.4.draft.docx)

**Comment by sdjmchattie** [comment]
A review of the systems we have already, what we need to determine and tasks that we need to get there are being captured in https://docs.google.com/document/d/1yT9qcKk_Is52Vjs-aSAaT4KeDLCu_ZqnuBv86mwvgxE/edit?usp=sharing

**Comment by ScottThurston** [comment]
Sample Preparation team Tecan cherrypicking SOP added above.
SM_PRO_0116 Cherry picking using the Tecan robot with disposable tips V1.4 draft.docx

**Comment by sdjmchattie** [comment]
There is a flow chart for the process here: https://lucid.app/lucidchart/5f1add24-46f9-45dc-a61e-a640a6b36d16/edit?invitationId=inv_651a7a89-fdfc-4eac-8568-d8115a364f49
