### ISSUE TITLE
DPL-670-4 Pass a Lighthouse specific API key to Sequencescape calls

### ISSUE THREAD

**Issue by sdjmchattie** [sanger/lighthouse#796]
**User story**
As a Lighthouse maintainer, I want to authenticate with a unique key when passing requests to Sequencescape.

**Who are the primary contacts for this story**
sm49 hc6

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Update the config for the app to accept an API key for Sequencescape calls on the v2 API.
- [x] Ensure the deployment project sets this key on deployed versions.
- [ ] Update the app to always provide this key in the headers for v2 SS endpoints.
- [ ] Redeploy with an app specific API key for Sequencescape.
- [ ] Check that requests coming from the app into Sequencescape are using the API key.

References
This story has a non-blocking relationship with:
- https://github.com/sanger/deployment/issues/314

**Comment by BenTopping** [comment]
Looks like this is already done? https://github.com/sanger/lighthouse/commit/ba102b84d4e71f06084bddb5e29dca24a0deb6b8
Maybe the intended target was lighthouse-ui?

**Comment by sdjmchattie** [comment]
Maybe it was done.  I doubt it since that commit was 2021.  I think the key to this issue was that there wasn't an API key specifically for Lighthouse to access SequenceScape before.  It was a generic one used across applications.  So if you have already updated the key in Lighthouse to have one that was made especially for it, then this probably is done, yes.

**Comment by BenTopping** [comment]
Hi Stuart, hope all is well 👋 . Checked the deployment project and lighthouse's prod config and it looks like it is using its own key now so going to close this issue. P.S You may get a few more notifications as we work through these stories sorry!
