### ISSUE TITLE
GPL-nnn Move positive reports into an openstack volume

### ISSUE THREAD

**Issue by emrojo** [sanger/lighthouse#86]
**User story**
All reports are stored in the root filesystem, which is decreasing available storage for other purposes. Same as we've done in crawler, it will be desirable to move the reports into its own openstack volume so it doesn't affect to other systems if the number of reports increases.

**Who are the primary contacts for this story**
Eduardo Martin

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] All reports stored in a new Openstack volume (not under / as it is happening now)

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by emrojo** [comment]
Proposed set of tasks:
- [ ] In psd-provision, create a new volume and attach the volume into dsm-swarm instance
- [ ] In psd-deployment, modify the docker_stack.yml and mount the new volume into the lighthouse reports folder

Then for each environment (uat, training, production):
- [ ] In psd-provision select the workspace (training)
- [ ] terraform apply (to create the volume; we dont have to restart the server, is automatically added as a new device (/dev folder)), to know the name check in dmesg output
- [ ] Log into the machine and create the filesystem in the new added device
```sudo mkfs.ext4 /dev/disk/by-id/virtio-cbec7cb1-***-***-***```
- [ ] Create a new folder to mount the filesystem
```sudo mkdir /var/lib/lighthouse-reports```
- [ ] Edit /etc/fstab and add the mount of the new filesystem in the new created folder
(It should do something like this):
```sudo mount /dev/disk/by-id/virtio-cbec7cb1-***-***-*** /var/lib/lighthouse-reports```
line like:
```/dev/vdxxx /var/lib/lighthouse-reports ext4 defaults 0 0```

**Comment by BenTopping** [comment]
Volume has been deployed and working on UAT
