### ISSUE TITLE
GPL-618 BUG - Cherrypicked column doesn't cope with repeat samples

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/lighthouse#91]
This is a bug coming out of the feature https://github.com/sanger/lighthouse/issues/84 (adding 'Cherrypicked' column to report).

We are setting the 'Cherrypicked' column in the 'Lighthouse positive samples report' by querying the Events warehouse to check if there has been a cherrypick event for that sample. Because we are matching based on the 'Root Sample ID', if we are sent a second plate that contains the same sample (as determined by Root Sample ID), the report will display 'Cherrypicked' : 'Yes' for the new sample as well as the old sample.

**Acceptance Criteria**
We should match based on plate barcode and well as well as Root Sample ID, so we can differentiate between instances of the same sample on different plates.

**Extra context**
Discussed with Rich C today. We agreed that:
* Repeat samples would be likely to sneak into cherrypick batches anyway, because the Lighthouse Sentinel feature selects **all** positive samples in a certain Labwhere location, whether or not they have been cherrypicked.
* Natalie uses the report as part of her wider reports and checks, so it would be good if the data was accurate despite the above.
* Rich is going to ask whether the institute wants to sequence repeat samples (if we get any), in a meeting later today

More insight on how the SSRs use the report:
* They run the report to identify positives on site.
* If they are creating a batch the normal / old way, they will copy-paste the 'plate and well' column into a cherrypick submission in Sequencescape
* If they are creating a batch the new way, they will grab the location barcodes for the positives they want to pick, and paste them into the Sentinel app
* With the new feature, they will filter the above report to only include samples that have not yet been cherrypicked
* Starting from next week, they will be receiving boxes of samples daily rather than the less frequent, larger deliveries, so will switch strategy to creating a cherrypick for boxes on the day they arrive.

**Comment by KatyTaylor** [comment]
N.B. as of [GPL-619](https://github.com/sanger/lighthouse/issues/97), 'Cherrypicked' column has been renamed to 'LIMS submission'.

**Comment by stevieing** [comment]
Not sure of the best way to UAT this. Is 'it works' good enough.
